name: daily-check

on:
  repository_dispatch:
  workflow_dispatch:
permissions:
  contents: write
  actions: write
jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: robinraju/release-downloader@v1
        with:
          repository: 'openwrt-fork/gecoos-crawler'
          latest: true
          fileName: 'gecoos-crawler'
          token: ${{ secrets.ORG_GITHUB_TOKEN }}
      - name: Test
        run: |
          chmod +x gecoos-crawler
          ./gecoos-crawler
