name: download firmware
on:
  workflow_call:
    inputs:
      tag:
        description: 'download tag'
        required: true
        type: string
      branch:
        description: 'git branch'
        required: true
        type: string

jobs:
  crawler:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.branch }}
      - uses: robinraju/release-downloader@v1
        with:
          repository: 'openwrt-fork/gecoos-crawler'
          latest: true
          fileName: 'gecoos-crawler'
          token: ${{ secrets.ORG_GITHUB_TOKEN }}
      - name: download firmwares
        run: |
          chmod +x gecoos-crawler
          ./gecoos-crawler download -t ${{ inputs.tag }}
